name: Build PR

on:
  pull_request:

jobs:
  generate_infos:
    uses: fullstack-devops/actions/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: Build "${{ matrix.arch }}"
        run: go build -v -ldflags "-X main.version=${{ needs.generate_infos.outputs.version }}" -o out/awesome-ci_${{ needs.generate_infos.outputs.version }}_${{ matrix.arch }}
        env:
          GOOS: linux
          GOARCH: "${{ matrix.arch }}"

      - name: debugging git
        if: matrix.arch == 'amd64'
        run: |
          echo "git name-rev HEAD: $(git name-rev HEAD)"
          echo "git log -1 --pretty=format:"%s": $(git log -1 --pretty=format:"%s")"
          echo "git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@': $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
      - name: test build Infos
        if: matrix.arch == 'amd64'
        run: out/awesome-ci_${{ needs.generate_infos.outputs.version }}_${{ matrix.arch }} pr info -number ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache build outputs
        uses: actions/cache@v2
        env:
          cache-name: cache-outputs-modules
        with:
          path: out/
          key: awesome-ci-${{ github.event.pull_request.head.sha }}-${{ hashFiles('out/awesome-ci*') }}
          restore-keys: |
            awesome-ci-${{ github.event.pull_request.head.sha }}

      #- name: Integration testing
      #  run: ./tools/test.sh ./out/awesome-ci_${ACI_NEXT_VERSION}_${{ matrix.arch }}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_release_test:
    runs-on: ubuntu-latest
    needs: [generate_infos, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: get cached build outputs
        uses: actions/cache@v2
        env:
          cache-name: cache-outputs-modules
        with:
          path: out/
          key: awesome-ci-${{ github.event.pull_request.head.sha }}

      - name: get generated artifacts
        working-directory: out
        run: ls -la

