name: Build PR

on:
  pull_request:

jobs:
  generate_infos:
    uses: fullstack-devops/actions/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - run: export
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: Build "${{ matrix.arch }}"
        run: make
        env:
          GOOS: linux
          GOARCH: "${{ matrix.arch }}"

      - name: debugging git
        if: matrix.arch == 'amd64'
        run: |
          echo "git name-rev HEAD: $(git name-rev HEAD)"
          echo "git log -1 --pretty=format:"%s": $(git log -1 --pretty=format:"%s")"
          echo "git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@': $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"

      - name: test build Infos
        id: test-build-infos
        if: matrix.arch == 'amd64'
        run: |
          build/package/awesome-ci_* pr info -n ${{ github.event.pull_request.number }} -v > $GITHUB_STEP_SUMMARY
          echo "out: $(cat $GITHUB_OUTPUT)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test env file
        if: matrix.arch == 'amd64'
        run: export | grep ACI_
      - name: test step export function
        if: matrix.arch == 'amd64'
        run: echo "${{ steps.test-build-infos.outputs.ACI_PR_BRANCH }}"

      - name: Cache build outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-outputs-modules
        with:
          path: build/package/
          key: awesome-ci-${{ github.event.pull_request.head.sha }}-${{ hashFiles('build/package/awesome-ci*') }}
          restore-keys: |
            awesome-ci-${{ github.event.pull_request.head.sha }}

      #- name: Integration testing
      #  run: ./tools/test.sh ./out/awesome-ci_${ACI_NEXT_VERSION}_${{ matrix.arch }}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_release_test:
    runs-on: ubuntu-latest
    needs: [generate_infos, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - run: echo "${{ needs.build.steps.test-build-infos.outputs.ACI_PR_BRANCH }}"

      - name: get cached build outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-outputs-modules
        with:
          path: build/package/
          key: awesome-ci-${{ github.event.pull_request.head.sha }}

      - name: get generated artifacts
        working-directory: build/package
        run: ls -la
