name: Build PR

on:
  pull_request:
    branches-ignore:
      - "docu/**"
    paths-ignore:
      - "README.md"
      - "docu/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"

jobs:
  generate_infos:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Set up awesome-ci
        run: |
          wget https://github.com/eksrvb/awesome-ci/releases/latest/download/awesome-ci
          chmod +x awesome-ci
      - id: tag
        shell: bash
        run: |
          echo "Tag: $(git describe --abbrev=0)"
          echo "::set-output name=version::$(awesome-ci pr info -format 'version')"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up awesome-ci
        run: |
          wget https://github.com/eksrvb/awesome-ci/releases/latest/download/awesome-ci
          chmod +x awesome-ci

      - name: debugging git
        run: |
          echo "git name-rev HEAD: $(git name-rev HEAD)"
          echo "git log -1 --pretty=format:"%s": $(git log -1 --pretty=format:"%s")"
          echo "git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@': $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
      - name: set build Infos
        run: ./awesome-ci getBuildInfos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build "${{ matrix.arch }}"
        run: go build -v -ldflags "-X main.version=$ACI_NEXT_VERSION" -o out/awesome-ci_${ACI_NEXT_VERSION}_${{ matrix.arch }}
        env:
          GOOS: linux
          GOARCH: "${{ matrix.arch }}"

      - name: get generated artifacts
        run: ls -la
      - name: Integration testing
        run: ./tools/test.sh ./out/awesome-ci_${ACI_NEXT_VERSION}_${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
