name: Publish Release

concurrency:
  group: ci-${{ github.repository }}-release
  cancel-in-progress: false

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"

jobs:
  create_release:
    uses: fullstack-devops/actions/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build "${{ matrix.arch }}"
        run: make VERSION="${{ needs.create_release.outputs.version }}"
        env:
          GOOS: linux
          GOARCH: "${{ matrix.arch }}"

      - name: Cache build outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-outputs-modules
        with:
          path: build/package/
          key: awesome-ci-${{ github.sha }}-${{ hashFiles('build/package/awesome-ci*') }}
          enableCrossOsArchive: true
          restore-keys: |
            awesome-ci-${{ github.sha }}

  publish_release:
    runs-on: ubuntu-latest
    needs: [create_release, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: get cached build outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-outputs-modules
        with:
          path: build/package/
          key: awesome-ci-${{ github.sha }}

      - name: get generated artifacts
        working-directory: build/package
        run: ls -la

      - name: Publish Release
        run: awesome-ci release publish -releaseid "$ACI_RELEASE_ID" -assets "file=build/package/$ARTIFACT1" -body "scripts/release-template.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACI_RELEASE_ID: ${{ needs.create_release.outputs.releaseid }}
          ARTIFACT1: awesome-ci_${{ needs.create_release.outputs.version }}_amd64

  update_action:
    runs-on: ubuntu-latest
    needs: [create_release, publish_release]
    steps:
      - name: Check out awesome-ci-action
        uses: actions/checkout@v3
        with:
          repository: fullstack-devops/awesome-ci-action
          token: ${{ secrets.ACI_REPO_TOKEN }}
          persist-credentials: true

      - name: Update version and push
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          OLD_VERSION=$(echo "$(git describe --tags)" | tr -d '\n')

          sed -i "s/\([0-9]\+\.[0-9]\+\.[0-9]\+\)/$NEW_VERSION/g" action.yml README.md

          git status
          git commit -a -m "update to version v$NEW_VERSION"
          git tag v$NEW_VERSION -m "update to version v$NEW_VERSION"
          git push --follow-tags
        env:
          NEW_VERSION: ${{ needs.create_release.outputs.version }}
