name: Publish Release

concurrency:
  group: ci-${{ github.repository }}-release
  cancel-in-progress: false

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "CHANGELOG.md"

jobs:
  create_release:
    uses: fullstack-devops/git-workflows/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make VERSION="${{ needs.create_release.outputs.version }}"

      - name: Test
        run: make test

      - name: create changelog & update release-template.md
        run: LATEST_VERSION="${{ needs.create_release.outputs.latest-version }}" make chglog

      - name: Cache build outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-outputs-modules
        with:
          path: build/package/
          key: awesome-ci-${{ github.sha }}-${{ hashFiles('build/package/awesome-ci*') }}
          restore-keys: |
            awesome-ci-${{ github.sha }}

  publish_release:
    environment: production
    runs-on: ubuntu-latest
    needs: [create_release, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main

      - name: get cached build outputs
        uses: actions/cache@v3
        env:
          cache-name: cache-outputs-modules
        with:
          path: build/package/
          key: awesome-ci-${{ github.sha }}

      - name: list generated artifacts
        working-directory: build/package
        run: ls -la

      - name: Publish Release
        run: >-
          awesome-ci release publish --release-id ${{ needs.create_release.outputs.releaseid }}
          -a "file=build/package/awesome-ci_${{ needs.create_release.outputs.version }}_linux-amd64"
          -a "file=build/package/awesome-ci_${{ needs.create_release.outputs.version }}_linux-arm64"
          -a "file=build/package/awesome-ci_${{ needs.create_release.outputs.version }}_windows-amd64.exe"
          -a "file=build/package/awesome-ci_${{ needs.create_release.outputs.version }}_windows-arm64.exe"
          -a "file=build/package/CHANGELOG.md"
          --body "build/package/release-template.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_action:
    runs-on: ubuntu-latest
    needs: [create_release, publish_release]
    steps:
      - name: Check out awesome-ci-action
        uses: actions/checkout@v3
        with:
          repository: fullstack-devops/awesome-ci-action
          token: ${{ secrets.ACI_REPO_TOKEN }}
          persist-credentials: true

      - name: Update version and push
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          sed -i "s/\([0-9]\+\.[0-9]\+\.[0-9]\+\)/$NEW_VERSION/g" action.yml README.md

          git status
          git commit -a -m "update to version v$NEW_VERSION"
          git tag v$NEW_VERSION -m "update to version v$NEW_VERSION"
          git push --follow-tags
        env:
          NEW_VERSION: ${{ needs.create_release.outputs.version }}
